configversion: 1.0.0
messagenotfound: "&cCe message n'a pas été trouvé ! Veuillez contacter un administrateur dès que possible !"
materialsverified:
  - "56:0"
  - "14:0"
  - "129:0"

#Ne compte pas les joueurs en créatif
creativebypass: true
#Montre les statistiques depuis la dernière session de minage des joueurs lors du /topluck
showlastonprofil: true